# Generated by Django 4.0.5 on 2022-09-09 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='item name')),
                ('description', models.TextField(blank=True, verbose_name='description of the item')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='price of the item')),
            ],
        ),
    ]
